[project]
name = "neuroquest"
version = "0.2.0"
description = "LLM powered textual RPG game"
readme = "readme.md"
requires-python = ">=3.14"
dependencies = [
    "baml-py>=0.222.0",
    "dotenv>=0.9.9",
    "loguru>=0.7.3",
    "markdown-it-py>=4.0.0",
    "pandas>=3.0.0",
    "pydantic>=2.12.5",
    "rich>=14.3.2",
    "sqlalchemy>=2.0.46",
    "poethepoet>=0.32.0",
    "langgraph>=1.2.9",
]

[build-system]
requires = ["setuptools>=75.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]

[tool.poe.tasks]
baml-gen = "baml-cli generate --from=src/baml_src"
