from typing import List, Generator
from rich.console import Console, Group
from rich.panel import Panel
from rich.text import Text
from rich.spinner import Spinner
from rich.live import Live
from llm_rpg.gui.console_manager import ConsoleManager
from llm_rpg.engine.game_ai import GameAI, HookResponse, InputProcessingStatus

import logging

logger = logging.getLogger(__name__)


class ChatInterface:
    """
    RPG chat interface designed for GameAI with Rich library.

    This class provides a visual chat interface that displays responses from
    the GameAI engine, including NPC dialogue and game action streams. It supports
    service commands (like /save, /lore, /exit) and allows extensibility through
    service command hooks.

    Response Types:
        - Static responses: Pre-generated text displayed in panels
        - NPC responses: Named panels with NPC-specific dialogue
        - Game responses: Streaming content displayed in real-time with mint_cyan text

    Service Commands:
        Built-in: /exit, !q (exit), /save, /lore
        Extensible via register_service_command()
    """

    def __init__(self, console_manager: ConsoleManager):
        """
        Initialize the ChatInterface.

        Args:
            console_manager: ConsoleManager instance providing console and styles.
                The console is used for all display operations, and styles provide
                the visual theme for different response types.
        """
        self.console = console_manager.console
        self.styles = console_manager.styles
        self.running = False

        self.game_ai = None
        self.__exit_kws = {"/exit", "!q"}

        self.service_commands = ["/exit", "!q", "/save", "/lore"]
        self.service_command_hooks = {}


    def set_game_ai(self, game_ai: GameAI) -> None:
        """
        Inject a GameAI instance for processing user input.

        This method follows dependency injection pattern, allowing the chat
        interface to work with any GameAI instance without creating its own.

        Args:
            game_ai: The GameAI instance to use for processing user inputs
                and generating responses.
        """
        self.game_ai = game_ai


    def _show_typing_indicator(self) -> Group:
        """
        Create an animated typing indicator display.

        Returns a Rich Group containing a spinner and "Thinking..." text
        that indicates the system is processing user input.

        Returns:
            Group: A Rich Group widget containing the typing indicator.
                The indicator uses the 'typing' style for visual consistency.
        """
        return Group(
            Spinner('dots', style=self.styles.get_style("typing")),
            Text("Thinking...", style=self.styles.get_style("typing"))
        )


    def _display_static_response(self, response: str, title: str) -> None:
        """
        Display a pre-generated response in a styled panel.

        This method is used for responses that do not require streaming,
        such as non-game actions or system messages. The response text
        uses the 'llm_output' style and has an RPG-themed border.

        Args:
            response: The text content to display in the panel.
            title: The title displayed at the top of the panel.
                For NPC responses, this would be the NPC's name.
        """
        panel = Panel(
            Text(response, style=self.styles.get_style("llm_output")),
            title=title,
            border_style=self.styles.get_style("rpg_npc"),
            subtitle_align="right"
        )
        self.console.print(panel)


    def _display_npc_response(self, npc_name: str, response: str) -> None:
        """
        Display an NPC's dialogue in a dedicated panel.

        This method formats and displays responses from NPCs with their
        name as the panel title, making it clear which character is
        speaking. Uses the standard RPG styling for consistency.

        Args:
            npc_name: The name of the NPC whose response is being displayed.
                This appears as the panel title.
            response: The dialogue text generated by the NPC's AI.
        """
        panel = Panel(
            Text(response, style=self.styles.get_style("llm_output")),
            title=npc_name,
            border_style=self.styles.get_style("rpg_npc"),
            subtitle_align="right"
        )
        self.console.print(panel)


    def _display_game_response_stream(self, stream: Generator[str, None, None], title: str = "Game Response") -> None:
        """
        Display a streaming response with real-time updates.

        This method handles game action responses that are generated
        incrementally. It uses Rich's Live display to show content
        being appended in real-time, providing a satisfying typing effect.

        The streaming response uses special styling:
        - Text: 'game_stream' style (mint_cyan color, bold)
        - Panel border: 'game_stream_panel' style (bright_yellow)

        Args:
            stream: A generator yielding string chunks of the response.
                Each chunk is appended to the display as it arrives.
            title: Optional title for the response panel. Defaults to
                "Game Response" for standard game action streams.
        """
        from rich.style import Style

        full_response = []

        def get_panel():
            return Panel(
                Text("".join(full_response), style=self.styles.get_style("game_stream")),
                title=title,
                border_style=self.styles.get_style("game_stream_panel"),
                subtitle_align="right"
            )

        with Live(get_panel(), refresh_per_second=12, console=self.console) as live:
            for chunk in stream:
                full_response.append(chunk)
                live.update(get_panel())


    def _process_service_command(self, command: str) -> None:
        """
        Route and execute a service command.

        Service commands are special in-game commands that perform
        administrative or informational functions rather than game actions.
        The method routes commands to registered hooks, default handlers,
        or reports unknown commands.

        Command Routing:
            1. Check if command has a registered hook -> execute hook
            2. Check if command is a built-in service command -> execute default handler
            3. Report unknown command

        Args:
            command: The full command string input by the user, including
                any arguments (e.g., "/save my_save_file").
        """
        cmd_parts = command.split()
        base_cmd = cmd_parts[0]

        if base_cmd in self.service_command_hooks:
            self.console.print(
                Text(f"Processing: {base_cmd}", style=self.styles.get_style("service_command"))
            )
            self.service_command_hooks[base_cmd](cmd_parts[1:] if len(cmd_parts) > 1 else None)
        elif base_cmd in self.service_commands:
            self._execute_default_handler(base_cmd)
        else:
            self.console.print(
                Text(f"Unknown command: {base_cmd}", style=self.styles.get_style("error"))
            )


    def _execute_default_handler(self, command: str) -> None:
        """
        Execute built-in service command handlers.

        This method routes known service commands to their corresponding
        handler methods. It is called when a command matches the built-in
        service commands list but has no registered hook.

        Built-in Commands:
            /exit, !q -> _handle_exit(): Terminate the game session
            /save -> _handle_save(): Save game state (placeholder)
            /lore -> _handle_lore(): Display world lore (placeholder)

        Args:
            command: The base command string to execute (without arguments).
        """
        if command in {"/exit", "!q"}:
            self._handle_exit()
        elif command == "/save":
            self._handle_save()
        elif command == "/lore":
            self._handle_lore()


    def register_service_command(self, command: str, handler) -> None:
        """
        Register a custom handler for a service command.

        This method allows extending the chat interface with new service
        commands beyond the built-in ones. Registered handlers receive
        any command arguments as a list of strings.

        Command Registration Flow:
            1. Command is added to service_commands list
            2. Handler is stored in service_command_hooks dict
            3. Future calls to this command will execute the registered handler

        Args:
            command: The command string users will type (e.g., "/stats").
                Should start with '/' for clarity but this is not enforced.
            handler: A callable that accepts one argument (args: List[str] | None).
                The args parameter contains any space-separated arguments
                provided after the command.
        """
        self.service_commands.append(command)
        self.service_command_hooks[command] = handler
        logger.info(f"Registered \"{command}\" as service command")


    def _handle_exit(self) -> None:
        """
        Handle termination of the game session.

        Displays an exit message to the user and sets the running
        flag to False, which causes the main chat loop in start()
        to terminate gracefully.
        """
        self.console.print(Text("Exiting game...", style=self.styles.get_style("success")))
        self.running = False


    def _handle_save(self) -> None:
        """
        Handle saving the current game state.

        This is a placeholder implementation that acknowledges the save
        command. A full implementation would serialize game state to disk,
        including lore, player state, inventory, and turn history.

        See CC_chat2-GenAI_refactor_v1.md Section 8.2 for implementation ideas.
        """
        self.console.print(Text("Game saved!", style=self.styles.get_style("success")))


    def _handle_lore(self) -> None:
        """
        Display world lore information.

        This is a placeholder implementation that shows basic lore data
        when the /lore command is invoked. A full implementation would
        display comprehensive world information including kingdoms, towns,
        and other lore elements in styled panels.

        See CC_chat2-GenAI_refactor_v1.md Section 8.3 for implementation ideas.
        """
        if self.game_ai and self.game_ai.lore:
            world_name = self.game_ai.lore.get('world', {}).get('name', 'Unknown')
            self.console.print(Text(f"World Lore: {world_name}", style=self.styles.get_style("info")))
        else:
            self.console.print(Text("No lore available", style=self.styles.get_style("error")))


    def start(self) -> None:
        """
        Run the main event loop for the chat interface.

        This method enters an infinite loop that:
            1. Displays a welcome message
            2. Prompts the user for input with "You: " prefix
            3. Processes input via _process_user_input()
            4. Continues until running flag is set to False

        The loop handles KeyboardInterrupt gracefully, ensuring the
        session ends cleanly with an appropriate message.

        Event Loop Flow:
            ┌─────────────────────┐
            │   Set running=True  │
            └──────────┬──────────┘
                       │
                       ▼
            ┌─────────────────────┐
            │  Show welcome panel │
            └──────────┬──────────┘
                       │
                       ▼
            ┌─────────────────────┐
            │  Get user input     │
            └──────────┬──────────┘
                       │
                       ▼
            ┌─────────────────────┐
            │  Process input      │
            │  (NPC responses,    │
            │   game stream)      │
            └──────────┬──────────┘
                       │
                       └───[ loop while running ]

        Args:
            None

        Raises:
            KeyboardInterrupt: Caught and handled to allow graceful exit.
        """
        self.running = True
        self.console.print(
            Panel("Welcome to the RPG Chat!", style=self.styles.get_style("rpg_system"))
        )

        try:
            while self.running:
                user_input = self.console.input(
                    Text("You: ", style=self.styles.get_style("rpg_player"))
                ).strip()

                self._process_user_input(user_input)

        except KeyboardInterrupt:
            self.running = False
        finally:
            self.console.print("Chat session ended.", style=self.styles.get_style("system"))


    def _process_user_input(self, user_input: str) -> None:
        """
        Process user input and route to appropriate handlers.

        This is the main input processing method that determines whether
        user input is a service command or a game action, then routes it
        to the appropriate handler.

        Processing Flow:
            1. Check if input is a service command (starts with / or !)
            2. If service command: route via _process_service_command()
            3. If game action: pass to GameAI.process_user_input()

        Service Command Detection:
            - Commands starting with '/' are treated as service commands
            - Commands in __exit_kws are also treated as service commands
            - Unknown service commands trigger error message

        Args:
            user_input: The raw string input provided by the user.
                This may be a service command or a game action.
        """
        # Check if this is a service command
        if user_input.startswith('/') or user_input in self.__exit_kws:
            self._process_service_command(user_input)
            return

        # Check for exit keywords (like !q)
        if user_input in self.__exit_kws:
            self._handle_exit()
            return

        # Process as game action
        if not self.game_ai:
            self.console.print(
                Text("Error: GameAI not initialized. Call set_game_ai() first.", style=self.styles.get_style("error"))
            )
            return

        # Show typing indicator while processing
        typing_group = self._show_typing_indicator()
        self.console.print(typing_group)

        try:
            responses = self.game_ai.process_user_input(user_input)

            # Handle NPC responses (if any)
            for response in responses:
                if response.role != "GAME":
                    self._display_npc_response(response.role, response.message)
                else:
                    # Game responses may be static or streaming
                    if self.game_ai.is_game_response_generated():
                        stream = self.game_ai.get_game_action_stream()
                        self._display_game_response_stream(stream)

        except Exception as e:
            logger.error(f"Error processing user input: {e}")
            self.console.print(
                Text(f"Error processing input: {str(e)}", style=self.styles.get_style("error"))
            )